# Generated by Django 5.1 on 2024-09-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_user_eur_account_alter_user_usd_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
