# Generated by Django 5.1 on 2024-09-22 01:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
